"""Add durable work plans, dependency graphs, and outbound issue records."""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "c7d8e9f0a1b2"
down_revision = "b6f7a8b9c0d1"
branch_labels = None
depends_on = None

def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_plans',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('repository', sa.String(length=255), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('base_branch', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'id')
    )
    op.create_index(op.f('ix_work_plans_project_id'), 'work_plans', ['project_id'], unique=False)
    op.create_table('work_issue_mirrors',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('desired', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('synced_digest', sa.String(length=64), nullable=True),
    sa.Column('issue_number', sa.Integer(), nullable=True),
    sa.Column('issue_id', sa.BigInteger(), nullable=True),
    sa.Column('issue_url', sa.String(length=2048), nullable=True),
    sa.Column('create_attempted', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_token', sa.Uuid(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['work_plans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id')
    )
    op.create_index(op.f('ix_work_issue_mirrors_plan_id'), 'work_issue_mirrors', ['plan_id'], unique=False)
    op.create_table('work_items',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('acceptance', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ai_catalog_id', sa.UUID(), nullable=True),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=True),
    sa.Column('execution_id', sa.Uuid(), nullable=True),
    sa.Column('pipeline_run_retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('base_sha', sa.String(length=64), nullable=True),
    sa.Column('pull_number', sa.Integer(), nullable=True),
    sa.Column('pull_url', sa.String(length=2048), nullable=True),
    sa.Column('merge_sha', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_token', sa.Uuid(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_catalog_id'], ['ai_catalogs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['work_plans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_run_id'),
    sa.UniqueConstraint('plan_id', 'id'),
    sa.UniqueConstraint('plan_id', 'key')
    )
    op.create_index(op.f('ix_work_items_plan_id'), 'work_items', ['plan_id'], unique=False)
    op.create_index(op.f('ix_work_items_state'), 'work_items', ['state'], unique=False)
    op.create_table('work_plan_dependencies',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('depends_on_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('plan_id <> depends_on_id', name='ck_work_plan_no_self_dependency'),
    sa.ForeignKeyConstraint(['project_id', 'depends_on_id'], ['work_plans.project_id', 'work_plans.id'], ),
    sa.ForeignKeyConstraint(['project_id', 'plan_id'], ['work_plans.project_id', 'work_plans.id'], ),
    sa.PrimaryKeyConstraint('plan_id', 'depends_on_id')
    )
    op.create_table('work_item_dependencies',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('depends_on_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('item_id <> depends_on_id', name='ck_work_item_no_self_dependency'),
    sa.ForeignKeyConstraint(['plan_id', 'depends_on_id'], ['work_items.plan_id', 'work_items.id'], ),
    sa.ForeignKeyConstraint(['plan_id', 'item_id'], ['work_items.plan_id', 'work_items.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'depends_on_id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_item_dependencies')
    op.drop_table('work_plan_dependencies')
    op.drop_index(op.f('ix_work_items_state'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_plan_id'), table_name='work_items')
    op.drop_table('work_items')
    op.drop_index(op.f('ix_work_issue_mirrors_plan_id'), table_name='work_issue_mirrors')
    op.drop_table('work_issue_mirrors')
    op.drop_index(op.f('ix_work_plans_project_id'), table_name='work_plans')
    op.drop_table('work_plans')
    # ### end Alembic commands ###
