"""update

Revision ID: 061a3a930c1e
Revises: d6e7f8a9b0c1
Create Date: 2026-09-16 22:26:03.495090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '061a3a930c1e'
down_revision: Union[str, None] = 'd6e7f8a9b0c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipeline_runs', 'pull_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Immutable pull request task specification captured at enrollment',
               existing_nullable=False)
    op.alter_column('schedule_configs', 'next_run_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of the next scheduled execution. NULL indicates this schedule should be executed immediately by the dispatcher.',
               existing_comment='Timestamp of the next scheduled execution',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule_configs', 'next_run_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of the next scheduled execution',
               existing_comment='Timestamp of the next scheduled execution. NULL indicates this schedule should be executed immediately by the dispatcher.',
               existing_nullable=True)
    op.alter_column('pipeline_runs', 'pull_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Immutable pull request task specification captured at enrollment',
               existing_nullable=False)
    # ### end Alembic commands ###
