"""init

Revision ID: d6e7f8a9b0c1
Revises: 
Create Date: 2026-09-16 22:14:31.122043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6e7f8a9b0c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connectors',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Unique connector name'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='External service provider'),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, comment='Non-sensitive provider configuration'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('credentials_ciphertext', sa.LargeBinary(), nullable=False, comment='AES-GCM encrypted credential JSON including the authentication tag'),
    sa.Column('credentials_nonce', sa.LargeBinary(), nullable=False, comment='Unique 12-byte AES-GCM nonce'),
    sa.Column('credential_key_version', sa.String(length=255), nullable=False, comment='Secret Manager version used to encrypt credentials'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_connectors_provider'), 'connectors', ['provider'], unique=False)
    op.create_table('github_webhook_deliveries',
    sa.Column('delivery_id', sa.String(length=255), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('repository', sa.String(length=255), nullable=True),
    sa.Column('payload_digest', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_id')
    )
    op.create_index(op.f('ix_github_webhook_deliveries_repository'), 'github_webhook_deliveries', ['repository'], unique=False)
    op.create_table('schedule_configs',
    sa.Column('name', sa.String(), nullable=False, comment='Human-readable name of the schedule'),
    sa.Column('description', sa.String(), nullable=True, comment='Optional description of what this schedule does'),
    sa.Column('task_func', sa.String(), nullable=False, comment="Dotted path to the task function to execute (e.g. 'tasks.send_report')"),
    sa.Column('cron_expression', sa.String(), nullable=True, comment="Cron expression for time-based scheduling (e.g. '0 9 * * 1-5'). Mutually exclusive with interval_seconds"),
    sa.Column('interval_seconds', sa.Integer(), nullable=True, comment='Fixed interval in seconds between executions. Mutually exclusive with cron_expression'),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, comment='Arbitrary JSON payload passed to the task function as kwargs'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Whether this schedule is active and should be picked up by the dispatcher'),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True, comment='Optional datetime after which the schedule becomes active'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True, comment='Optional datetime after which the schedule is no longer executed'),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the most recent execution'),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the next scheduled execution. NULL indicates this schedule should be executed immediately by the dispatcher.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_schedule_configs_enabled_next_run_at', 'schedule_configs', ['enabled', 'next_run_at'], unique=False)
    op.create_index(op.f('ix_schedule_configs_last_run_at'), 'schedule_configs', ['last_run_at'], unique=False)
    op.create_index(op.f('ix_schedule_configs_name'), 'schedule_configs', ['name'], unique=False)
    op.create_index(op.f('ix_schedule_configs_next_run_at'), 'schedule_configs', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_schedule_configs_task_func'), 'schedule_configs', ['task_func'], unique=False)
    op.create_table('system_configs',
    sa.Column('name', sa.String(), nullable=False, comment='Unique key identifying the system config entry'),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, comment='Arbitrary JSON data associated with this system config'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('task_states',
    sa.Column('config_id', sa.Uuid(), nullable=False, comment='ScheduleConfig id this state belongs to (from the task execution context).'),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, comment='Opaque, task-owned state blob.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_table('ai_catalogs',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('adapter', sa.String(length=100), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('availability_state', sa.String(length=30), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('availability_source', sa.String(length=100), nullable=True),
    sa.Column('availability_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('availability_note', sa.Text(), nullable=True),
    sa.Column('configured_concurrency', sa.Integer(), nullable=False),
    sa.Column('refresh_jitter_minutes', sa.Integer(), nullable=False),
    sa.Column('policy_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('policy_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_ai_catalogs_available_at'), 'ai_catalogs', ['available_at'], unique=False)
    op.create_table('schedule_jobs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('schedule_config_id', sa.UUID(), nullable=True, comment='Reference to the schedule config that triggered this job execution.'),
    sa.Column('dispatcher_run_id', sa.Uuid(), nullable=True, comment='Reference to the dispatcher run that executed this job. This allows grouping multiple schedule jobs under a single dispatcher run for better traceability.'),
    sa.Column('status', sa.String(), nullable=False, comment='Execution status of the schedule.'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the task execution started.'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the task execution finished.'),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, comment='Snapshot of the payload used during execution.'),
    sa.Column('error_message', sa.String(), nullable=True, comment='Error message if the task execution failed.'),
    sa.Column('retry_need', sa.Boolean(), nullable=False, comment='Indicates whether this job needs to be retried. This can be set to True for failed jobs that should be retried by the dispatcher.'),
    sa.Column('retry_attempts', sa.Integer(), nullable=False, comment='Number of retry attempts that have been made for this job. This can be used by the dispatcher to implement retry logic with a maximum number of attempts.'),
    sa.Column('retry_max', sa.Integer(), nullable=False, comment='Maximum number of retry attempts allowed for this job. Once retry_attempts reaches this number, the job will no longer be retried.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['schedule_config_id'], ['schedule_configs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_jobs_dispatcher_run_id'), 'schedule_jobs', ['dispatcher_run_id'], unique=False)
    op.create_index(op.f('ix_schedule_jobs_finished_at'), 'schedule_jobs', ['finished_at'], unique=False)
    op.create_index(op.f('ix_schedule_jobs_name'), 'schedule_jobs', ['name'], unique=False)
    op.create_index('ix_schedule_jobs_retry_lookup', 'schedule_jobs', ['status', 'retry_need', 'retry_attempts'], unique=False)
    op.create_index(op.f('ix_schedule_jobs_schedule_config_id'), 'schedule_jobs', ['schedule_config_id'], unique=False)
    op.create_index(op.f('ix_schedule_jobs_started_at'), 'schedule_jobs', ['started_at'], unique=False)
    op.create_table('ai_catalog_dispatches',
    sa.Column('ai_catalog_id', sa.UUID(), nullable=False),
    sa.Column('dispatch_key', sa.String(length=200), nullable=False),
    sa.Column('admitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_catalog_id'], ['ai_catalogs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dispatch_key')
    )
    op.create_index('ix_ai_catalog_dispatches_catalog_admitted', 'ai_catalog_dispatches', ['ai_catalog_id', 'admitted_at'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('github_repository', sa.String(length=255), nullable=True),
    sa.Column('github_connector_id', sa.UUID(), nullable=True),
    sa.Column('ai_catalog_id', sa.UUID(), nullable=True),
    sa.Column('verification', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('automation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=50), nullable=True),
    sa.Column('template_version', sa.String(length=50), nullable=True),
    sa.Column('last_check', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_catalog_id'], ['ai_catalogs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['github_connector_id'], ['connectors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_repository')
    )
    op.create_table('pipeline_runs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('ai_catalog_id', sa.UUID(), nullable=False),
    sa.Column('requested_catalog_id', sa.UUID(), nullable=True),
    sa.Column('project_revision', sa.Integer(), nullable=False),
    sa.Column('github_repository', sa.String(length=255), nullable=True),
    sa.Column('github_connector_id', sa.Uuid(), nullable=True),
    sa.Column('pull_number', sa.Integer(), nullable=False),
    sa.Column('pull_url', sa.String(length=2048), nullable=False),
    sa.Column('pull_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, comment='Immutable pull request task specification captured at enrollment'),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('pause_reason', sa.Text(), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=255), nullable=True),
    sa.Column('lease_token', sa.Uuid(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quota_block_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('revision >= 1', name='ck_pipeline_runs_revision_positive'),
    sa.ForeignKeyConstraint(['ai_catalog_id'], ['ai_catalogs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_catalog_id'], ['ai_catalogs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_ai_catalog_id'), 'pipeline_runs', ['ai_catalog_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_lease_expires_at'), 'pipeline_runs', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_next_action_at'), 'pipeline_runs', ['next_action_at'], unique=False)
    op.create_index('ix_pipeline_runs_project_created', 'pipeline_runs', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_state'), 'pipeline_runs', ['state'], unique=False)
    op.create_index('uq_pipeline_runs_active_pull', 'pipeline_runs', ['project_id', 'pull_number'], unique=True, postgresql_where=sa.text("state IN ('queued', 'dispatching', 'implementing', 'awaiting_ci', 'paused', 'blocked')"), sqlite_where=sa.text("state IN ('queued', 'dispatching', 'implementing', 'awaiting_ci', 'paused', 'blocked')"))
    op.create_table('project_agent_schedules',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('schedule_config_id', sa.UUID(), nullable=False),
    sa.Column('ai_catalog_id', sa.UUID(), nullable=False),
    sa.Column('work_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('starting_branch', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_catalog_id'], ['ai_catalogs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['schedule_config_id'], ['schedule_configs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_config_id')
    )
    op.create_index(op.f('ix_project_agent_schedules_ai_catalog_id'), 'project_agent_schedules', ['ai_catalog_id'], unique=False)
    op.create_index(op.f('ix_project_agent_schedules_project_id'), 'project_agent_schedules', ['project_id'], unique=False)
    op.create_table('ai_catalog_sessions',
    sa.Column('ai_catalog_id', sa.UUID(), nullable=False),
    sa.Column('schedule_config_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('work_type', sa.String(length=20), nullable=False),
    sa.Column('repository', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('external_name', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('pull_request_url', sa.String(length=2048), nullable=True),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_catalog_id'], ['ai_catalogs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_config_id'], ['schedule_configs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_name')
    )
    op.create_index(op.f('ix_ai_catalog_sessions_ai_catalog_id'), 'ai_catalog_sessions', ['ai_catalog_id'], unique=False)
    op.create_index(op.f('ix_ai_catalog_sessions_pipeline_run_id'), 'ai_catalog_sessions', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_ai_catalog_sessions_schedule_config_id'), 'ai_catalog_sessions', ['schedule_config_id'], unique=False)
    op.create_index(op.f('ix_ai_catalog_sessions_state'), 'ai_catalog_sessions', ['state'], unique=False)
    op.create_table('execution_attempts',
    sa.Column('pipeline_run_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('request_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('request_digest', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.Uuid(), nullable=False),
    sa.Column('external_correlation_id', sa.String(length=255), nullable=True),
    sa.Column('external_status', sa.String(length=100), nullable=True),
    sa.Column('conversation_url', sa.String(length=2048), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt_number >= 1', name='ck_execution_attempts_number_positive'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_correlation_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_execution_attempts_pipeline_run_id'), 'execution_attempts', ['pipeline_run_id'], unique=False)
    op.create_index('uq_execution_attempts_run_number', 'execution_attempts', ['pipeline_run_id', 'attempt_number'], unique=True)
    op.create_table('execution_deliveries',
    sa.Column('execution_attempt_id', sa.UUID(), nullable=False),
    sa.Column('delivery_number', sa.Integer(), nullable=False),
    sa.Column('cause', sa.String(length=30), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('delivery_number >= 1', name='ck_execution_deliveries_number_positive'),
    sa.ForeignKeyConstraint(['execution_attempt_id'], ['execution_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_execution_deliveries_execution_attempt_id'), 'execution_deliveries', ['execution_attempt_id'], unique=False)
    op.create_index('uq_execution_deliveries_attempt_number', 'execution_deliveries', ['execution_attempt_id', 'delivery_number'], unique=True)
    op.create_table('execution_replies',
    sa.Column('execution_attempt_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('is_quota_limit', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_attempt_id'], ['execution_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_execution_replies_execution_attempt_id'), 'execution_replies', ['execution_attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_replies_execution_attempt_id'), table_name='execution_replies')
    op.drop_table('execution_replies')
    op.drop_index('uq_execution_deliveries_attempt_number', table_name='execution_deliveries')
    op.drop_index(op.f('ix_execution_deliveries_execution_attempt_id'), table_name='execution_deliveries')
    op.drop_table('execution_deliveries')
    op.drop_index('uq_execution_attempts_run_number', table_name='execution_attempts')
    op.drop_index(op.f('ix_execution_attempts_pipeline_run_id'), table_name='execution_attempts')
    op.drop_table('execution_attempts')
    op.drop_index(op.f('ix_ai_catalog_sessions_state'), table_name='ai_catalog_sessions')
    op.drop_index(op.f('ix_ai_catalog_sessions_schedule_config_id'), table_name='ai_catalog_sessions')
    op.drop_index(op.f('ix_ai_catalog_sessions_pipeline_run_id'), table_name='ai_catalog_sessions')
    op.drop_index(op.f('ix_ai_catalog_sessions_ai_catalog_id'), table_name='ai_catalog_sessions')
    op.drop_table('ai_catalog_sessions')
    op.drop_index(op.f('ix_project_agent_schedules_project_id'), table_name='project_agent_schedules')
    op.drop_index(op.f('ix_project_agent_schedules_ai_catalog_id'), table_name='project_agent_schedules')
    op.drop_table('project_agent_schedules')
    op.drop_index('uq_pipeline_runs_active_pull', table_name='pipeline_runs', postgresql_where=sa.text("state IN ('queued', 'dispatching', 'implementing', 'awaiting_ci', 'paused', 'blocked')"), sqlite_where=sa.text("state IN ('queued', 'dispatching', 'implementing', 'awaiting_ci', 'paused', 'blocked')"))
    op.drop_index(op.f('ix_pipeline_runs_state'), table_name='pipeline_runs')
    op.drop_index('ix_pipeline_runs_project_created', table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_next_action_at'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_lease_expires_at'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_ai_catalog_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_table('projects')
    op.drop_index('ix_ai_catalog_dispatches_catalog_admitted', table_name='ai_catalog_dispatches')
    op.drop_table('ai_catalog_dispatches')
    op.drop_index(op.f('ix_schedule_jobs_started_at'), table_name='schedule_jobs')
    op.drop_index(op.f('ix_schedule_jobs_schedule_config_id'), table_name='schedule_jobs')
    op.drop_index('ix_schedule_jobs_retry_lookup', table_name='schedule_jobs')
    op.drop_index(op.f('ix_schedule_jobs_name'), table_name='schedule_jobs')
    op.drop_index(op.f('ix_schedule_jobs_finished_at'), table_name='schedule_jobs')
    op.drop_index(op.f('ix_schedule_jobs_dispatcher_run_id'), table_name='schedule_jobs')
    op.drop_table('schedule_jobs')
    op.drop_index(op.f('ix_ai_catalogs_available_at'), table_name='ai_catalogs')
    op.drop_table('ai_catalogs')
    op.drop_table('task_states')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_schedule_configs_task_func'), table_name='schedule_configs')
    op.drop_index(op.f('ix_schedule_configs_next_run_at'), table_name='schedule_configs')
    op.drop_index(op.f('ix_schedule_configs_name'), table_name='schedule_configs')
    op.drop_index(op.f('ix_schedule_configs_last_run_at'), table_name='schedule_configs')
    op.drop_index('ix_schedule_configs_enabled_next_run_at', table_name='schedule_configs')
    op.drop_table('schedule_configs')
    op.drop_index(op.f('ix_github_webhook_deliveries_repository'), table_name='github_webhook_deliveries')
    op.drop_table('github_webhook_deliveries')
    op.drop_index(op.f('ix_connectors_provider'), table_name='connectors')
    op.drop_table('connectors')
    # ### end Alembic commands ###
